version: '2'
services:

  db:
    image: mysql:5.6
    ports: 
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
      #- ./db/expenses_schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenses_management_v1
      MYSQL_USER: amdh
      MYSQL_PASSWORD: root

  ws:
    build: ws/.
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    #entrypoint: ./wait_for_db.sh db:3306

    # type 2
    #db:
#    build: db/.
 #   volumes:
  #    - /var/lib/mysql
   #   - ./db/expenses_schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    #environment:
     #  MYSQL_ROOT_PASSWORD: root